"""Initial migration

Revision ID: 25a084b70984
Revises: 
Create Date: 2024-11-20 02:22:02.135882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a084b70984'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('damage', sa.String(length=20), nullable=True),
    sa.Column('range', sa.String(length=20), nullable=True),
    sa.Column('ap', sa.Integer(), nullable=True),
    sa.Column('rof', sa.Integer(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('min_str', sa.String(length=10), nullable=True),
    sa.Column('armor', sa.Integer(), nullable=True),
    sa.Column('coverage', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index('idx_item_name', ['name'], unique=False)
        batch_op.create_index('idx_item_type', ['item_type'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_username', ['username'], unique=False)

    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('setting', sa.String(length=100), nullable=True),
    sa.Column('power_level', sa.String(length=50), nullable=True),
    sa.Column('available_races', sa.String(length=1000), nullable=True),
    sa.Column('available_edges', sa.String(length=1000), nullable=True),
    sa.Column('house_rules', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('next_session', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.create_index('idx_campaign_name', ['name'], unique=False)
        batch_op.create_index('idx_campaign_owner_id', ['owner_id'], unique=False)
        batch_op.create_index('idx_campaign_status', ['status'], unique=False)

    op.create_table('campaign_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'campaign_id')
    )
    op.create_table('campaign_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_note', schema=None) as batch_op:
        batch_op.create_index('idx_note_author', ['created_by'], unique=False)
        batch_op.create_index('idx_note_campaign', ['campaign_id'], unique=False)
        batch_op.create_index('idx_note_type', ['note_type'], unique=False)

    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('race', sa.String(length=50), nullable=False),
    sa.Column('character_concept', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.String(length=20), nullable=True),
    sa.Column('agility', sa.String(length=3), nullable=True),
    sa.Column('smarts', sa.String(length=3), nullable=True),
    sa.Column('spirit', sa.String(length=3), nullable=True),
    sa.Column('strength', sa.String(length=3), nullable=True),
    sa.Column('vigor', sa.String(length=3), nullable=True),
    sa.Column('hindrances', sa.Text(), nullable=True),
    sa.Column('edges', sa.Text(), nullable=True),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index('idx_character_campaign_id', ['campaign_id'], unique=False)
        batch_op.create_index('idx_character_name', ['name'], unique=False)
        batch_op.create_index('idx_character_user_id', ['user_id'], unique=False)

    op.create_table('map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('map_type', sa.String(length=50), nullable=False),
    sa.Column('grid_width', sa.Integer(), nullable=False),
    sa.Column('grid_height', sa.Integer(), nullable=False),
    sa.Column('background_color', sa.String(length=7), nullable=False),
    sa.Column('show_grid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.create_index('idx_map_campaign', ['campaign_id'], unique=False)
        batch_op.create_index('idx_map_creator', ['created_by'], unique=False)
        batch_op.create_index('idx_map_name', ['name'], unique=False)

    op.create_table('character_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('equipped', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_inventory', schema=None) as batch_op:
        batch_op.create_index('idx_inventory_character', ['character_id'], unique=False)
        batch_op.create_index('idx_inventory_equipped', ['equipped'], unique=False)
        batch_op.create_index('idx_inventory_item', ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_inventory', schema=None) as batch_op:
        batch_op.drop_index('idx_inventory_item')
        batch_op.drop_index('idx_inventory_equipped')
        batch_op.drop_index('idx_inventory_character')

    op.drop_table('character_inventory')
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_index('idx_map_name')
        batch_op.drop_index('idx_map_creator')
        batch_op.drop_index('idx_map_campaign')

    op.drop_table('map')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index('idx_character_user_id')
        batch_op.drop_index('idx_character_name')
        batch_op.drop_index('idx_character_campaign_id')

    op.drop_table('character')
    with op.batch_alter_table('campaign_note', schema=None) as batch_op:
        batch_op.drop_index('idx_note_type')
        batch_op.drop_index('idx_note_campaign')
        batch_op.drop_index('idx_note_author')

    op.drop_table('campaign_note')
    op.drop_table('campaign_members')
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_index('idx_campaign_status')
        batch_op.drop_index('idx_campaign_owner_id')
        batch_op.drop_index('idx_campaign_name')

    op.drop_table('campaign')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_username')
        batch_op.drop_index('idx_user_email')

    op.drop_table('user')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index('idx_item_type')
        batch_op.drop_index('idx_item_name')

    op.drop_table('item')
    # ### end Alembic commands ###
